import CNNAProofs.C008

open CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.RecordLiveResponseCoupledUpdate

#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.RecordLiveResponseCoupledUpdate.applyInstruction_respects_sameValue
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.RecordLiveResponseCoupledUpdate.RecordLiveResponseCoupledUpdateContract
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.RecordLiveResponseCoupledUpdate.recordLiveResponseCoupledUpdateContract
#print axioms CNNAProofs.C008.CanonicalRecordLiveUpdateClosure
#print axioms CNNAProofs.C008.canonicalRecordLiveUpdateClosure
#print axioms CNNAProofs.C008.CanonicalRecordLiveUpdateContract
#print axioms CNNAProofs.C008.canonicalRecordLiveUpdateContract
