import CNNAProofs.C009

#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.CodomainStateX.assemble_respects_sameValue
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.CodomainStateX.codomainAssembly_existsUnique
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.CodomainStateX.CodomainStateAssemblyContract
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.CodomainStateX.codomainStateAssemblyContract
#print axioms CNNAProofs.C009.CanonicalCodomainStateAssemblyClosure
#print axioms CNNAProofs.C009.canonicalCodomainStateAssemblyClosure
#print axioms CNNAProofs.C009.CanonicalCodomainStateAssemblyContract
#print axioms CNNAProofs.C009.canonicalCodomainStateAssemblyContract
