import CNNAProofs.C016C017

open CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.ImmutableRecordChannel
open CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.CurrentLiveChannel

#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.ImmutableRecordChannel.afterInstruction_respects_sameValue
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.ImmutableRecordChannel.ImmutableRecordChannelContract
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.ImmutableRecordChannel.immutableRecordChannelContract
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.CurrentLiveChannel.afterInstruction_respects_sameValue
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.CurrentLiveChannel.CurrentLiveChannelContract
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.CurrentLiveChannel.currentLiveChannelContract
#print axioms CNNAProofs.C016C017.CanonicalImmutableRecordChannelClosure
#print axioms CNNAProofs.C016C017.canonicalImmutableRecordChannelClosure
#print axioms CNNAProofs.C016C017.CanonicalCurrentLiveChannelClosure
#print axioms CNNAProofs.C016C017.canonicalCurrentLiveChannelClosure
#print axioms CNNAProofs.C016C017.CanonicalRecordLiveChannelProjectionContract
#print axioms CNNAProofs.C016C017.canonicalRecordLiveChannelProjectionContract
