import CNNAProofs.T002

#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering.NextOpenProvenanceSlot.successorBornPrefixClosure
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering.BirthLocalSchurDtnPrimitive.ExactFraction.toRat_eq_of_sameValue
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering.BirthLocalSchurDtnPrimitive.ExactFraction.toRat_represents
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering.BirthLocalSchurDtnPrimitive.ExactFraction.toRat_pos_of_num_pos
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering.InterBirthDirectedResponse.canonicalStateDirectedBlockRealization
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering.InterBirthDirectedResponse.stateDirectedBlockRealization_exists
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering.ResponseCapableState.conductancePairsUnique_append
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering.CanonicalBirthLocalMeasurementCut.PortSupportClosure
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering.CanonicalBirthLocalMeasurementCut.portSupportClosure
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering.ResponseCoupledBirthLawBirthlawB.LiveRelationDeltaClosure
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering.ResponseCoupledBirthLawBirthlawB.liveRelationDeltaClosure
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering.ResponseCoupledBirthLawBirthlawB.liveRelationDelta_positiveNum
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.RecurrentStateClosureTheorem.realizedLiveDelta_sameValue
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.RecurrentStateClosureTheorem.successorConductances_pairwise
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.RecurrentStateClosureTheorem.successor_parentBackbone
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.RecurrentStateClosureTheorem.successor_live_coherent
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.RecurrentStateClosureTheorem.RecurrentStateClosure
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.RecurrentStateClosureTheorem.recurrentStateClosure
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.RecurrentStateClosureTheorem.RecurrentStateClosureContract
#print axioms CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S04_RecordLiveUpdateBackreactionChannelsAndFiniteClosure.RecurrentStateClosureTheorem.recurrentStateClosureContract
#print axioms CNNAProofs.T002.canonicalRecurrentStepInput_exists
#print axioms CNNAProofs.T002.canonicalRecurrentStateClosure_exists
#print axioms CNNAProofs.T002.CanonicalRecurrentStateClosure
#print axioms CNNAProofs.T002.canonicalRecurrentStateClosure
#print axioms CNNAProofs.T002.CanonicalRecurrentStateClosureContract
#print axioms CNNAProofs.T002.canonicalRecurrentStateClosureContract
