import Init.PropLemmas
import Init.Data.List.Lemmas
import Init.Data.List.Sublist
import Init.Data.List.FinRange
import CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering.S02_C004_NextOpenProvenanceSlotSnplus1NGe1

/-!
Paper 1.3.4 / M001 — canonical birth-local measurement cut `Cₙ(sₙ₊₁)`.

M001 consumes exactly a recurrent C005 state `Xₙ` and its C004 next open
provenance slot.  It does not perform Schur/DtN elimination and introduces no
response value, sampling cap, geometric radius, unborn node, or additional
model parameter.

The birth-local boundary is obtained by restricting C005's canonical current
carrier order to two provenance roles already fixed by the C004 slot:

* the root-to-parent prefix chain of the slot parent; and
* same-parent sibling addresses with local rank strictly below the next rank.

The interior is the complementary ordered subsequence of that same born
carrier.  Thus M001 defines a block partition and a block order, but no new
ordering convention: both blocks inherit their order from C005/C018.

Python constructs these two filtered tuples directly.  Lean characterizes the
same object by the same finite provenance predicate and proves uniqueness,
carrier support, disjointness, exhaustiveness, and exclusion of the unborn C004
child.
-/

namespace CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering

open CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S01_PrimitiveInputsGrammarAndEventOrder
open NextOpenProvenanceSlot

namespace CanonicalBirthLocalMeasurementCut

/-- C005's canonical current-carrier order: root first, followed by the C018
born non-root prefix. -/
def canonicalCarrier (X : ResponseCapableState) :
    List (ProvenanceAddress X.grammar.branching) :=
  ResponseCapableState.rootAddress X :: X.bornNonRoot

/-- Construct all successive provenance prefixes from `pref` through the
remaining word.  For `pref=[]`, the output is root-to-address order. -/
def prefixChainAux {b : BranchingParameter}
    (pref : ProvenanceAddress b) : ProvenanceAddress b → List (ProvenanceAddress b)
  | [] => [pref]
  | rank :: rest => pref :: prefixChainAux (pref ++ [rank]) rest

/-- Every address generated by `prefixChainAux pref rest` is a genuine
prefix of the final provenance word `pref ++ rest`.  This is the structural
bridge needed to prove that no intended causal port can disappear silently
from the born carrier. -/
theorem prefixChainAux_mem_prefix {b : BranchingParameter}
    {pref rest a : ProvenanceAddress b}
    (h : a ∈ prefixChainAux pref rest) :
    List.IsPrefix a (pref ++ rest) := by
  induction rest generalizing pref with
  | nil =>
      change a ∈ [pref] at h
      have ha : a = pref := List.mem_singleton.mp h
      rw [ha]
      exact List.prefix_append pref []
  | cons localRank tail ih =>
      change a ∈ pref :: prefixChainAux (pref ++ [localRank]) tail at h
      have hCases : a = pref ∨ a ∈ prefixChainAux (pref ++ [localRank]) tail :=
        List.mem_cons.mp h
      cases hCases with
      | inl ha =>
          rw [ha]
          exact List.prefix_append pref (localRank :: tail)
      | inr hTail =>
          have hPrefix := ih hTail
          have hWord :
              (pref ++ [localRank]) ++ tail = pref ++ (localRank :: tail) := by
            exact List.append_assoc pref [localRank] tail
          exact hWord ▸ hPrefix

/-- Root-to-parent causal predecessor ports fixed by the C004 slot. -/
def causalPredecessorPorts {X : ResponseCapableState} (next : NextOpenSlot X) :
    List (ProvenanceAddress X.grammar.branching) :=
  prefixChainAux [] (parentAddress next)

/-- Same-parent sibling ports whose local rank is strictly earlier than the
C004 rank.  `Fin (rank next).val` makes the strict-rank domain constructive. -/
def olderSiblingPorts {X : ResponseCapableState} (next : NextOpenSlot X) :
    List (ProvenanceAddress X.grammar.branching) :=
  (List.finRange (rank next).val).map fun earlier =>
    ProvenanceAddress.snoc (parentAddress next)
      ⟨earlier.val, Nat.lt_trans earlier.isLt (rank next).isLt⟩

/-- The language-independent M001 port predicate. -/
def BirthLocalPort {X : ResponseCapableState} (next : NextOpenSlot X)
    (a : ProvenanceAddress X.grammar.branching) : Prop :=
  a ∈ causalPredecessorPorts next ∨ a ∈ olderSiblingPorts next

/-- Every intended root-to-parent causal port is already present in the C005
carrier.  Python checks this executable handoff; Lean proves it from C004
minimality and the finite provenance order. -/
theorem causalPredecessorPort_born {X : ResponseCapableState}
    (next : NextOpenSlot X)
    {a : ProvenanceAddress X.grammar.branching}
    (hPort : a ∈ causalPredecessorPorts next) :
    NodeBorn X.grammar X.bornNonRoot a := by
  have hPrefix : List.IsPrefix a (parentAddress next) := by
    unfold causalPredecessorPorts at hPort
    have h := prefixChainAux_mem_prefix hPort
    change List.IsPrefix a (parentAddress next) at h
    exact h
  by_cases hRoot : a = ProvenanceAddress.root X.grammar.branching
  · exact Or.inl hRoot
  · apply Or.inr
    have hNonroot : ProvenanceAddress.depth a ≠ 0 := by
      intro hDepth
      exact hRoot (eq_root_of_depth_eq_zero a hDepth)
    obtain ⟨suffix, hPrefixEq⟩ := hPrefix
    have hDepthLeParent :
        ProvenanceAddress.depth a ≤
          ProvenanceAddress.depth (parentAddress next) := by
      unfold ProvenanceAddress.depth
      have hLengths := congrArg List.length hPrefixEq
      rw [List.length_append] at hLengths
      exact Nat.le.intro hLengths
    have hChildCutoff := child_withinCutoff next
    rw [child_eq_snoc next, ProvenanceAddress.depth_snoc] at hChildCutoff
    have hParentCutoff :
        ProvenanceAddress.depth (parentAddress next) ≤ X.grammar.cutoff.value :=
      Nat.le_trans
        (Nat.le_succ (ProvenanceAddress.depth (parentAddress next)))
        hChildCutoff
    have hCutoff : ProvenanceAddress.depth a ≤ X.grammar.cutoff.value :=
      Nat.le_trans hDepthLeParent hParentCutoff
    have hBefore : CanonicalBirthSchedule.BirthBefore a next.val := by
      apply CanonicalBirthSchedule.shallower_before
      rw [child_eq_snoc next, ProvenanceAddress.depth_snoc]
      exact Nat.lt_succ_iff.mpr hDepthLeParent
    exact earlier_admissible_is_born next a hNonroot hCutoff hBefore

/-- Every same-parent rank strictly earlier than the C004 rank is already born.
This is the theorem-level counterpart of Python's `missing_siblings` guard. -/
theorem olderSiblingPort_born {X : ResponseCapableState}
    (next : NextOpenSlot X)
    {a : ProvenanceAddress X.grammar.branching}
    (hPort : a ∈ olderSiblingPorts next) :
    NodeBorn X.grammar X.bornNonRoot a := by
  unfold olderSiblingPorts at hPort
  obtain ⟨earlier, _hRange, hAddress⟩ := List.mem_map.mp hPort
  let localRank : ProvenanceSlot X.grammar.branching :=
    ⟨earlier.val, Nat.lt_trans earlier.isLt (rank next).isLt⟩
  have hAddress' :
      ProvenanceAddress.snoc (parentAddress next) localRank = a := by
    exact hAddress
  rw [← hAddress']
  apply Or.inr
  have hNonroot :
      ProvenanceAddress.depth
        (ProvenanceAddress.snoc (parentAddress next) localRank) ≠ 0 := by
    rw [ProvenanceAddress.depth_snoc]
    exact Nat.succ_ne_zero _
  have hChildCutoff := child_withinCutoff next
  rw [child_eq_snoc next, ProvenanceAddress.depth_snoc] at hChildCutoff
  have hCutoff :
      ProvenanceAddress.depth
          (ProvenanceAddress.snoc (parentAddress next) localRank) ≤
        X.grammar.cutoff.value := by
    rw [ProvenanceAddress.depth_snoc]
    exact hChildCutoff
  have hBefore :
      CanonicalBirthSchedule.BirthBefore
        (ProvenanceAddress.snoc (parentAddress next) localRank) next.val := by
    rw [child_eq_snoc next]
    apply CanonicalBirthSchedule.sameParentIncreasingRank
    change localRank.val < (rank next).val
    exact earlier.isLt
  exact earlier_admissible_is_born next
    (ProvenanceAddress.snoc (parentAddress next) localRank)
    hNonroot hCutoff hBefore

/-- Thus every M001 role named by the common Python/Lean port predicate is a
real already-born port, not merely a name that may be dropped by filtering. -/
theorem birthLocalPort_born {X : ResponseCapableState}
    (next : NextOpenSlot X)
    {a : ProvenanceAddress X.grammar.branching}
    (hPort : BirthLocalPort next a) :
    NodeBorn X.grammar X.bornNonRoot a := by
  cases hPort with
  | inl hCausal => exact causalPredecessorPort_born next hCausal
  | inr hSibling => exact olderSiblingPort_born next hSibling

private instance birthLocalPortDecidable {X : ResponseCapableState}
    (next : NextOpenSlot X) (a : ProvenanceAddress X.grammar.branching) :
    Decidable (BirthLocalPort next a) := by
  unfold BirthLocalPort
  infer_instance

/-- Boolean realization used only to filter the finite carrier. -/
def portFlag {X : ResponseCapableState} (next : NextOpenSlot X)
    (a : ProvenanceAddress X.grammar.branching) : Bool :=
  decide (BirthLocalPort next a)

/-- Ordered M001 boundary: restrict the C005 carrier order to birth-local ports. -/
def boundary {X : ResponseCapableState} (next : NextOpenSlot X) :
    List (ProvenanceAddress X.grammar.branching) :=
  (canonicalCarrier X).filter (portFlag next)

/-- Ordered M001 interior: the complementary C005 carrier subsequence. -/
def interior {X : ResponseCapableState} (next : NextOpenSlot X) :
    List (ProvenanceAddress X.grammar.branching) :=
  (canonicalCarrier X).filter fun a => !(portFlag next a)

/-- The C006-facing M001 block partition. -/
structure BirthLocalMeasurementCut (X : ResponseCapableState) where
  boundary : List (ProvenanceAddress X.grammar.branching)
  interior : List (ProvenanceAddress X.grammar.branching)

/-- Canonical executable cut object on the Lean side. -/
def canonicalCut (X : ResponseCapableState) (next : NextOpenSlot X) :
    BirthLocalMeasurementCut X where
  boundary := boundary next
  interior := interior next

/-- Extensional characterization shared with Python. -/
def IsCanonicalCut {X : ResponseCapableState} (next : NextOpenSlot X)
    (cut : BirthLocalMeasurementCut X) : Prop :=
  cut.boundary = boundary next ∧ cut.interior = interior next

/-- The constructor satisfies the extensional M001 characterization. -/
theorem canonicalCut_isCanonical (X : ResponseCapableState) (next : NextOpenSlot X) :
    IsCanonicalCut next (canonicalCut X next) :=
  ⟨rfl, rfl⟩

/-- The extensional M001 characterization identifies exactly one block object. -/
theorem unique {X : ResponseCapableState} (next : NextOpenSlot X)
    (left right : BirthLocalMeasurementCut X)
    (hLeft : IsCanonicalCut next left)
    (hRight : IsCanonicalCut next right) : left = right := by
  cases left with
  | mk leftBoundary leftInterior =>
      cases right with
      | mk rightBoundary rightInterior =>
          change leftBoundary = boundary next ∧ leftInterior = interior next at hLeft
          change rightBoundary = boundary next ∧ rightInterior = interior next at hRight
          have hBoundary : leftBoundary = rightBoundary :=
            hLeft.1.trans hRight.1.symm
          have hInterior : leftInterior = rightInterior :=
            hLeft.2.trans hRight.2.symm
          cases hBoundary
          cases hInterior
          rfl

/-- Membership in the canonical carrier is exactly C005 born-carrier membership. -/
theorem carrier_mem_implies_born {X : ResponseCapableState}
    {a : ProvenanceAddress X.grammar.branching}
    (h : a ∈ canonicalCarrier X) : NodeBorn X.grammar X.bornNonRoot a := by
  cases h with
  | head => exact Or.inl rfl
  | tail _ hTail => exact Or.inr hTail

/-- Conversely, C005 born-carrier membership is exactly membership in the
ordered `canonicalCarrier` used by M001. -/
theorem born_implies_carrier_mem {X : ResponseCapableState}
    {a : ProvenanceAddress X.grammar.branching}
    (h : NodeBorn X.grammar X.bornNonRoot a) : a ∈ canonicalCarrier X := by
  cases h with
  | inl hRoot =>
      rw [hRoot]
      exact List.Mem.head X.bornNonRoot
  | inr hBorn =>
      exact List.Mem.tail (ResponseCapableState.rootAddress X) hBorn

/-- No intended M001 port can be silently discarded by the carrier filter. -/
theorem birthLocalPort_mem_boundary {X : ResponseCapableState}
    (next : NextOpenSlot X)
    {a : ProvenanceAddress X.grammar.branching}
    (hPort : BirthLocalPort next a) : a ∈ boundary next := by
  apply List.mem_filter.mpr
  constructor
  · exact born_implies_carrier_mem (birthLocalPort_born next hPort)
  · change portFlag next a = true
    unfold portFlag
    exact decide_eq_true_iff.mpr hPort

/-- Lean's executable boundary is extensionally exactly the common M001 port
predicate, matching Python's role set rather than merely a subset of it. -/
theorem boundary_mem_iff_birthLocalPort {X : ResponseCapableState}
    (next : NextOpenSlot X)
    (a : ProvenanceAddress X.grammar.branching) :
    a ∈ boundary next ↔ BirthLocalPort next a := by
  constructor
  · intro hBoundary
    have hFlag := (List.mem_filter.mp hBoundary).2
    change portFlag next a = true at hFlag
    unfold portFlag at hFlag
    exact decide_eq_true_iff.mp hFlag
  · intro hPort
    exact birthLocalPort_mem_boundary next hPort

/-- Every boundary address is an already-born C005 node. -/
theorem boundary_node_born {X : ResponseCapableState} (next : NextOpenSlot X)
    {a : ProvenanceAddress X.grammar.branching}
    (h : a ∈ boundary next) : NodeBorn X.grammar X.bornNonRoot a := by
  have hFilter := (List.mem_filter.mp h).1
  exact carrier_mem_implies_born hFilter

/-- Every interior address is an already-born C005 node. -/
theorem interior_node_born {X : ResponseCapableState} (next : NextOpenSlot X)
    {a : ProvenanceAddress X.grammar.branching}
    (h : a ∈ interior next) : NodeBorn X.grammar X.bornNonRoot a := by
  have hFilter := (List.mem_filter.mp h).1
  exact carrier_mem_implies_born hFilter

/-- Boundary and interior never overlap. -/
theorem boundary_interior_disjoint {X : ResponseCapableState} (next : NextOpenSlot X)
    (a : ProvenanceAddress X.grammar.branching)
    (hBoundary : a ∈ boundary next) (hInterior : a ∈ interior next) : False := by
  have hb := (List.mem_filter.mp hBoundary).2
  have hi := (List.mem_filter.mp hInterior).2
  cases hFlag : portFlag next a with
  | false =>
      rw [hFlag] at hb
      cases hb
  | true =>
      rw [hFlag] at hi
      cases hi

/-- Every born carrier address belongs to exactly one of the two M001 blocks. -/
theorem carrier_covered {X : ResponseCapableState} (next : NextOpenSlot X)
    (a : ProvenanceAddress X.grammar.branching)
    (hCarrier : a ∈ canonicalCarrier X) :
    a ∈ boundary next ∨ a ∈ interior next := by
  cases hFlag : portFlag next a with
  | false =>
      apply Or.inr
      apply List.mem_filter.mpr
      constructor
      · exact hCarrier
      · change (!(portFlag next a)) = true
        rw [hFlag]
        rfl
  | true =>
      apply Or.inl
      apply List.mem_filter.mpr
      constructor
      · exact hCarrier
      · change portFlag next a = true
        exact hFlag

/-- The unborn C004 child is not in the current C005 carrier. -/
theorem child_not_in_carrier {X : ResponseCapableState} (next : NextOpenSlot X) :
    next.val ∉ canonicalCarrier X := by
  intro hCarrier
  have hBorn : NodeBorn X.grammar X.bornNonRoot next.val :=
    carrier_mem_implies_born hCarrier
  cases hBorn with
  | inl hRoot =>
      apply child_ne_nil next
      unfold ProvenanceAddress.root at hRoot
      exact hRoot
  | inr hBorn =>
      exact (child_notBorn next) hBorn

/-- Therefore the pre-birth M001 boundary never contains the unborn child. -/
theorem child_not_in_boundary {X : ResponseCapableState} (next : NextOpenSlot X) :
    next.val ∉ boundary next := by
  intro h
  exact child_not_in_carrier next (List.mem_filter.mp h).1

/-- Nor can the unborn child occur in the M001 interior. -/
theorem child_not_in_interior {X : ResponseCapableState} (next : NextOpenSlot X) :
    next.val ∉ interior next := by
  intro h
  exact child_not_in_carrier next (List.mem_filter.mp h).1


end CanonicalBirthLocalMeasurementCut

end CNNA.Derivation.S01_PrimitiveResponseCoupledFiniteProvenance.S03_RecurrentPreBirthMeasurementAndSteering
